services:
  mosquitto:
    image: eclipse-mosquitto
    ports: ["1883:1883"]

  influxdb:
    image: influxdb:2
    ports: ["8086:8086"]
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
      - DOCKER_INFLUXDB_INIT_ORG=velib
      - DOCKER_INFLUXDB_INIT_BUCKET=velib

  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]
    depends_on:
      - influxdb
    volumes:
      - grafana:/var/lib/grafana

  collector:
    build: .
    command: uv run src/collector.py
    env_file: .env
    environment:
      - MQTT_BROKER=mosquitto
      - CSV_PATH=/data/bandwidth.csv
    volumes:
      - ./data:/data
    depends_on:
      - mosquitto
    restart: unless-stopped

  processor:
    build: .
    command: uv run src/processor.py
    env_file: .env
    environment:
      - MQTT_BROKER=mosquitto
      - INFLUXDB_URL=http://influxdb:8086
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    depends_on:
      - mosquitto
      - influxdb
    restart: unless-stopped

volumes:
  influxdb_data:
  grafana:
